### ISSUE TITLE
running `jspm install` in demo folder fails

### ISSUE THREAD

**Issue by adriatic** [abalmus/aurelia-ace-editor#1]
`jspm install` results with 

```
...
     Looking up github:twbs/bootstrap
     Looking up github:ajaxorg/ace-builds
     Downloading github:abalmus/aurelia-ace-editor@master

warn Error on processPackageConfig
     Package.json dependency ace set to github:ajaxorg/ace-builds@^1.2.3, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error: Error processing package config for github:abalmus/aurelia-ace-editor.
         at C:\work\aurelia-tools\aurelia-ace-editor\node_modules\systemjs-builder\lib\builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (C:\work\aurelia-tools\aurelia-ace-editor\node_modules\rsvp\dist\rsvp.js:245:13)
         at null._onTimeout (C:\work\aurelia-tools\aurelia-ace-editor\node_modules\rsvp\dist\rsvp.js:568:47)
         at Timer.listOnTimeout (timers.js:92:15)
     Looking up npm:aurelia-loader
...
```

**Comment by abalmus** [comment]
Ok let me check this and get back to you!

**Comment by abalmus** [comment]
@adriatic, Fixed this issue https://github.com/abalmus/aurelia-ace-editor/commit/e38a30f8e4acc39ab58fe36f40adf433424516f9 , please check it out and let me know if it works for you. Also you will need to run `npm install` from root folder, so `browser-sync` will be installed.

**Comment by Thanood** [comment]
Works for me after the change. :smile:

**Comment by abalmus** [comment]
Great than I'll close it ;)

**Comment by Thanood** [comment]
Let's hope it works for @adriatic, too. Sometimes we have differing experiences. :wink:
